### ISSUE TITLE
Error when verifying

### ISSUE THREAD

**Issue by diegoherranz** [fransschreuder/usbpicprog#8]
I have an HEX file for PIC18F2550 which includes code and config (not data eeprom). Any kind of code/data/config protection is disabled.

I program the device with "Verify after programming" enabled and code, config and data verification enabled. The device is programmed correctly and the message is:
> Verify Successful

So far so good. However, if afterwards I press the "Verify" button, it fails saying:
>Verify config failed at 0x300000. Read: 0xFF, Expected: 0x00":

If I read the device back, the configration bits read are OK.

Doing some tests I noticed that the error only appears if you try to verify code and config at the same run. See this table:

| Verify Code | Verify Data | Verify Config | Result                                                       |
|:-----------:|:-----------:|:-------------:|:-------------------------------------------------------------|
|      NO     |      NO     |      YES      | Correct                                                      |
|      NO     |     YES     |       NO      | Correct                                                      |
|      NO     |     YES     |      YES      | Correct                                                      |
|     YES     |      NO     |       NO      | Correct                                                      |
|     YES     |      NO     |      YES      | Verify config failed at 0x300000. Read: 0xFF, Expected: 0x00 |
|     YES     |     YES     |       NO      | Correct                                                      |
|     YES     |     YES     |      YES      | Verify config failed at 0x300000. Read: 0xFF, Expected: 0x00 |

Then, I think that the first verification during programming works OK because code and data is verified first and config is verified later. ¿Right?

Do you have any clue where the problem is?

Thanks a lot!

PS: I noticed that using two different files, both having the same configuration bits but different code, only one of them shows this error while the other doesn't. So it seems that this bug is dependant of what's included in the code area.

PS2: usbpicprog 0.9.9-1.0.0-beta - 64 bit on Ubuntu GNOME 14.04 64 bits

**Comment by diegoherranz** [comment]
Finally I had time to test with external power and everything works fine, no problems any more. So, it had to be something related with power.

It's surprising that depending on the HEX file it could fail or not.

From now on, I will always use external power.

Thanks for your help!

**Comment by IMIKTechnology** [comment]
what is meant by USB error during verify

**Comment by IMIKTechnology** [comment]
how i'm supposed to fix it ...?

**Comment by fransschreuder** [comment]
Verify means that usbpicprog reads the code back that it just programmed, and checks it against what it just programmed. If the content doesn't match, it will tell you the address, the expected value and the read back value. It usually means that something went wrong.

**Comment by IMIKTechnology** [comment]
i'm getting this error while flashing..

**Comment by fransschreuder** [comment]
Of course you are, because "verify after programming" is enabled in settings. 
Now what is your question?
What device are you programming?
Is your hardware normally working?

**Comment by IMIKTechnology** [comment]
I'm using usbpicprog programmer...so while I try to flash i'm getting error as (USB error during verify) and also i'm getting another error followed by 1st one as (the hardware should say ok).I just want to know whether my programmer will work or not..

**Comment by fransschreuder** [comment]
Ok, please just answer my questions and give some more detail as I requested. I can't help you like this.

**Comment by IMIKTechnology** [comment]
i'm using usbpicprog by elementz pic programmer and flasher.http://elementzonline.com/usbpicprogrammer-by-elementz-pic-programmer-and-flasher-205?search=picprogrammer u can find in this website.I don't know whether it is working or not.When I try to burn my hex file i'm getting error what I mentioned above.

**Comment by fransschreuder** [comment]
Elementz is a company that made their own board, based on usbpicprog but not the same. I had multiple questions about non-working elementz boards, and it seems crappy engineered to me. 
Elementz is not at all related to usbpicprog, so please if you have malfunctioning hardware I would suggest you ask them to refund your money.
They are also violating the GPL by copying the hardware design, modifying it and not publishing the changes.
